# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: ubuntu:20.04


pipelines:
  default:
    - parallel:
        - step:
            name: Build and Run
            script:
              # install deps
              - apt-get update && apt-get install -y build-essential gcc-8 libopenmpi-dev libgsl-dev libhdf5-dev
              - apt-get install -y --no-install-recommends gosu
              - id -u build &>/dev/null || useradd --user-group --create-home --shell /bin/false build
              # build
              - gosu build make
              # Execute your C++ application after compilation to check success
              - gosu build sh run_testprob.sh
