# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: mcr.microsoft.com/azureml/base:openmpi3.1.2-ubuntu18.04


pipelines:
  default:
    - parallel:
        - step:
            name: Build and Run
            script:
              - make
              # Execute your C++ application after compilation to check success
              #- make distcheck
